### ISSUE TITLE
os-types.h:176: bad loop ?

### ISSUE THREAD

**Issue by dcb314** [janbar/cppmyth#3]
cppmyth-1.1.0.2/cppmyth/src/private/platform/posix/os-types.h:176]: (style) Array index 'i' is used before limits check.

  while(wc[i] && (i < n))

Suggest sanity check array index before use.

**Comment by janbar** [comment]
Thanks for the remark. This function provided by the header os-types.h is not use by cppmyth lib.
Also string 'wc' is a C string and so it has to be terminated by 0. The loop will exit first when wc[i] is 0 else when i = n, where n is max size of string to be copied into 's'.
Sure if 'wc' is not terminated with 0, probably program will crash on segment fault, but this case is out of scope.

**Comment by janbar** [comment]
The case is misleading but if you see other issue, please let me know and i will check. Thanks

**Comment by dcb314** [comment]
Suggest download static analyser cppcheck from sourceforge and then
you can check yourself.
