### ISSUE TITLE
Mythtv 0.28 incompatiblity

### ISSUE THREAD

**Issue by pellcorp** [janbar/cppmyth#5]
Because of commit:
https://github.com/MythTV/mythtv/commit/9f7d4d259f4192e5289242be0c7f956617f5ee7f

I get the following error in the logs:
AddOnLog: MythTV PVR Client: (CPPMyth)InitWSAPI: MythTV API service is not supported or unavailable: 127.0.0.1:6544 (5.0)

**Comment by janbar** [comment]
Thanks to report. I will update soon.
JLB

-----Original Message-----

**Comment by janbar** [comment]
FIxed with 1.1.10

**Comment by janbar** [comment]
Backported to kodi pvr helix (1.12.6) & gotham (1.9.22-39).
Ubuntu ppa is currently building ...

**Comment by pellcorp** [comment]
awesome work, thanks so much
